### ISSUE TITLE
Event time in server status block

### ISSUE THREAD

**Issue by ordeh** [tasks-delivery/MuOnline#102]
List with events time should be visible on the Left panel under list of servers.

 Each event should have name, start time, and will start in. Also, server time should be visible in the Event time block.

The 'Will Start in' is the countdown time from the start time of event

Time formats:
- Start time should have format HH:mm
- Will Start In should have format HH:mm:ss

![image](https://user-images.githubusercontent.com/25455982/127930607-82a28e19-4a7a-4c33-905c-2057184a487d.png)

**Comment by ordeh** [comment]
@andrei9619 
I think that  7 test-cases can be merged in one.

![image](https://user-images.githubusercontent.com/25455982/130348657-4f7119c6-00aa-46e6-8a95-dc3e8cb76167.png)

Test-case 'Will Start in' accuracy can be reworked.

- User not require logged in to the  system. I think that preconditions should have test for instance, 'Event with start time 12.00 exists in the system and now time is  11.55'. The same for other test cases, just say that the quest already exists in the system.
- Rework steps 3, we need to check how much time is left before the start of the quest
- I'm nor sure that  we need to use Input data field in the test-case

**Comment by andrei9619** [comment]
@ordeh 
Test cases were fixed
Ready to be reviewed

**Comment by ordeh** [comment]
@AndreiByin  please not forget that we have  bug related with this ticket https://github.com/tasks-delivery/MuOnline/issues/138

**Comment by AndreiByin** [comment]
@andrei9619 
I think it would be necessary to add an 'Event Time" check format of time "HH:mm:ss".
If possible, I ask you to do this.
