### ISSUE TITLE
Wrong stats count

### ISSUE THREAD

**Issue by ordeh** [tasks-delivery/MuOnline#110]
**Preconditions**: Account with character with more 33000 free stats exists in the system.

**Steps**:
1. Login in game as account from preconditions
2. Select character from preconditions and press enter key on keyboard
3. Press 'C' key on keyboard

**Actual result**: 32464 free stats are shown
![image](https://user-images.githubusercontent.com/25455982/126861571-05e996c0-036d-4d09-927d-9d44ee3dca07.png)
In db right value
![image](https://user-images.githubusercontent.com/25455982/126861468-48824ff4-c5c8-4db5-a7ef-7bca85f85ff8.png)

**Expexted result**: 98000 free stats are shown

**Comment by ordeh** [comment]
@andrei9619 
Test should be added in 'Stat' suite

**Comment by andrei9619** [comment]
Test located at
https://app.qase.io/case/WOMU/edit/45

**Comment by ordeh** [comment]
@andrei9619 
We need to say in the expected results that more than 33000 free points are displayed.

![image](https://user-images.githubusercontent.com/25455982/134634976-8d0865dd-e4ae-4b49-a581-dced259d72b5.png)
