### ISSUE TITLE
Rework lorencia map

### ISSUE THREAD

**Issue by ordeh** [tasks-delivery/MuOnline#113]
Remove the Christmas tree

![image](https://user-images.githubusercontent.com/25455982/126863532-22ddb355-79e1-42f0-9dc0-4ebba53b1d2b.png)

It future we will use Christmas tree only in december and january months.

**Comment by andrei9619** [comment]
What are the coordinates and which map is that location at?

**Comment by ordeh** [comment]
Hi @andrei9619  Lorencia map on  143 - 127

As expected result we wait figure of  waterflow  instead christmas tree.

**Comment by ordeh** [comment]
@andrei9619 
Please add link to test-case

**Comment by andrei9619** [comment]
Test located at 
https://app.qase.io/case/WOMU/edit/35
