### ISSUE TITLE
Rework texture message on notice element

### ISSUE THREAD

**Issue by ordeh** [tasks-delivery/MuOnline#115]
New  texture should have text 'WoMu'

![image](https://user-images.githubusercontent.com/25455982/126863745-c2ac8465-e1bd-4d6a-b097-32ce70da3546.png)

**Comment by ordeh** [comment]
Done

![image](https://user-images.githubusercontent.com/25455982/126915781-421f6e6f-6935-48d5-a0dc-83ff0213799e.png)

**Comment by ordeh** [comment]
@andrei9619
Test should be added to Texture suite

**Comment by andrei9619** [comment]
Test located at:
https://app.qase.io/case/WOMU/edit/32
