### ISSUE TITLE
App is crashed in not big resolution

### ISSUE THREAD

**Issue by ordeh** [tasks-delivery/MuOnline#118]
**Preconditions**: Screen resolutions is 1366x768 and account exists in the system

**Steps**:
1. Go to web application and type login of account from preconditions in the field 'login' on the login form.
2. Type a password that does not belong to an account with a precondition.
3. Select Exile x1000 server
4. Click Login

**Actual result**: Application is crashed and message box about invalid password  is not rendered.
**Expected result**: Application is not crashed and message box about invalid password is shown.

**Comment**: Defect is not always reprocude

**Comment by andrei9619** [comment]
Test located at:
https://app.qase.io/case/WOMU/edit/44
