### ISSUE TITLE
Statistic tab implementation

### ISSUE THREAD

**Issue by ordeh** [tasks-delivery/MuOnline#12]
Statistic tab should have several blocks

Block with general metrics with the following items:

- Server
- Server status
- Online
- Accounts
- Characters
- Guilds
- Version

Block with Castle Siege info with the following items:
- Castle owner
- Siege time
- Chronology of cycles
- Registered guilds

Block with Crywolf info with the following items:

- Fortress status
- Attack time

Block with Classes info with the following items:

- Magic Gladiator 
- Duel Master
- Dark Lord 
- Lord Emperor 
- Dark Wizard
- Soul Master 
- Grand Master 
- Dark Knight
- Blade Knight 
- Blade Master
- Elf 
- Muse Elf
- High Elf
- Summoner
- Bloody Summoner
- Dimension Master

**Comment by ordeh** [comment]
Done.
Castle siege guild list  and Crywolf info will be added in another issue #87  and #89

**Comment by ordeh** [comment]
There are 9 states of Castle siege event.

//----------------------------------------------------------------------//
// Castle Settings                                                      //
//----------------------------------------------------------------------//

//State   StartDay   StartHour   StartMinute
	1	    0	         0             0      // Register Period  Пн.
	2	    1	        23	        59      // Idle Вс.
	3	    2	         0	         0      // Register Mark Of The Lord Ср. 00.00 по Сб. 00.00
	4	    5	         0	         0      // Idle  Сб. с 00.00 до 12.00
	5	    5	        12	         0      // Castle Attack Guild Notification Сб.  с 12.00 до 19.00
	6	    5	        19	         0      // Ready For Castle Siege Сб. с 19.00 
	7	    6	        19	         0      // Castle Siege Start  Вс.
	8	    6	        21	         0      // Castle Siege End   Вс.
	9	    7           0              0      // End of Cycle

**Comment by AndreiByin** [comment]
@andrei9619 
I think it would be necessary to add an 'Event Time" check. 
If possible, I ask you to do this.
