### ISSUE TITLE
Sound effect

### ISSUE THREAD

**Issue by ordeh** [tasks-delivery/MuOnline#123]
Add sound and music effects to game client. 

It is possible to turn off/on sound effect from game client in options box
![image](https://user-images.githubusercontent.com/25455982/132873225-7173ac66-9892-4b83-970e-c1e76c05cb9a.png)

**Comment by ordeh** [comment]
@andrei9619
Test should be added to Should Effects suite

**Comment by andrei9619** [comment]
Test located at:
https://app.qase.io/case/WOMU/edit/34

**Comment by ordeh** [comment]
@andrei9619 

Add check that sound can be off/on the same for music effect.

**Comment by andrei9619** [comment]
@ordeh 
Fixed
