### ISSUE TITLE
Stats setup component

### ISSUE THREAD

**Issue by ordeh** [tasks-delivery/MuOnline#130]
As a user of the game, I would like to be able to distribute stat points of my character. The service of distribution stat points should be in the list of other services.

The stat point setup page should display information about the character's current str, agi, ene, vit, com and how many free stat points he has at the moment.

The user should be able to select any character on his account to setup stat points. If the user has selected a character with classes Dark lord or Lord of Empire, we should display command value of this character, for all other classes, command should always be 0.

If you setup stat points, but have not selected a character, the system should display an error message with a text '**You did not select a character**'.

Also, a prerequisite is the absence of an account connection to the game. If the account is online the system should display an error message with text '**The account must not be connected to the game while adding stat points..**'.

The stat point service should not allow the user to distribute more than the allowed limit of maximum stat points on the server. For example, the maximum number of stat points on the Exile server is 32767 

If the maximum allowable value of stat points is exceeded, then the system should display a message with text. '**You can only add {maxStatPointsValue} points.**'.

**maxStatPointsValue** - stat points limit for server

If the user tries to distribute more stats than he has, then the system should display a message with text '**You have not enough free stats.**'.

If the user tries to setup negative value in stat point field, for instance -1 then the system should display a message with text '**You cannot set the value less than 0**'.

if the user tries to distribute stats with a non-numerical value, the system will give him an error with a text '**Stat values can only be numeric**'.

**Comment by ordeh** [comment]
@andrei9619 
Could you provide links to test-cases?

**Comment by andrei9619** [comment]
@ordeh 
Test cases located at:
1. Stats setup page - https://app.qase.io/case/WOMU/edit/78
2. Stats setup page grid functionality - https://app.qase.io/case/WOMU/edit/93
3. Stats setup page (negative) - https://app.qase.io/case/WOMU/edit/99

**Comment by ordeh** [comment]
**In test-case https://app.qase.io/case/WOMU/edit/78**

Why do we need point 4?
![image](https://user-images.githubusercontent.com/25455982/144298821-5f3053c7-18d0-417e-ad91-56423a60a9c7.png)


**In test-case https://app.qase.io/case/WOMU/edit/93**
The items 1 and 3 should be moved to test-case https://app.qase.io/case/WOMU/edit/99
![image](https://user-images.githubusercontent.com/25455982/144299643-d3665b44-a4c9-489f-b0b7-a9fb5ca5da25.png)


**In test-case https://app.qase.io/case/WOMU/edit/99**
Why do we need points 1, 4 and 5?
![image](https://user-images.githubusercontent.com/25455982/144299338-32d536a1-3d60-48a5-a1e2-8267b073101f.png)

**Comment by andrei9619** [comment]
@ordeh 
For the test case https://app.qase.io/case/WOMU/edit/93
* In the step # 4 we check that user cannot add greater values then free stats
![Screen Shot 2021-12-05 at 10 09 11 PM](https://user-images.githubusercontent.com/61422820/144780868-8866c75f-d90a-4f97-9535-218e1d65d40f.png)
* In the step # 8 we also have expected result #2 it says about that all values become 0
![Screen Shot 2021-12-05 at 10 09 31 PM](https://user-images.githubusercontent.com/61422820/144780890-00cc8bf8-5c60-4678-b429-fb99b609035c.png)

**Comment by ordeh** [comment]
@andrei9619 

Regadring test-case https://app.qase.io/case/WOMU/edit/93

I asked to move these checks to another test case because we need to automate this.
![image](https://user-images.githubusercontent.com/25455982/145004628-a8993e1c-5153-446f-96cb-8cb0302e3261.png)

**Comment by andrei9619** [comment]
@ordeh 
Got in now 
Fixed

* Here is a new list of test cases:
1. Stats setup functionality when game client is online https://app.qase.io/case/WOMU/edit/125
2. Stats setup page grid functionality https://app.qase.io/case/WOMU/edit/93
3. Stats setup page https://app.qase.io/case/WOMU/edit/78
4. Status setup negative https://app.qase.io/case/WOMU/edit/99

**Comment by ordeh** [comment]
@andrei9619 

Rework all test descriptions where you use the words "all" "correct"

Test-case 78:

add text
![image](https://user-images.githubusercontent.com/25455982/146832737-ff54347a-81d7-4634-b359-09727ef262a1.png)

**Comment by veyron812** [comment]
@ordeh 
corrected test-cases

Stats setup page https://app.qase.io/case/WOMU/edit/78
Stats setup page grid functionality https://app.qase.io/case/WOMU/edit/93
Status setup negative https://app.qase.io/case/WOMU/edit/99
Stats setup functionality when game client is online https://app.qase.io/case/WOMU/edit/125
Stats setup https://app.qase.io/project/WOMU?suite=28&case=127
