### ISSUE TITLE
Wrong 'will start in' time (Timer)

### ISSUE THREAD

**Issue by andrei9619** [tasks-delivery/MuOnline#138]
**Precondition:** 
1.  At least one event exists in the system
2. User located at the GMT-4 time zone 
3. Event start time - 20:00
4. Server time - 10:24:54

**Steps to reproduce:**
1. Open the web application
2. Scroll down to the 'Event time' block

**Actual result:** Timer shows incorrect time left to the event start (Different time zones of the host and user) 
**Expected result:** Timer shows correct time left till the event start

**Environment:** 
Mac OS, Google Chrome

![Screen Shot 2021-08-27 at 10 24 55 AM](https://user-images.githubusercontent.com/61422820/131143025-3bed68e6-0d4e-4d41-a96a-18af90edd2a8.png)

**Comment by AndreiByin** [comment]
@andrei9619
I think it would be necessary to add an 'Event Time" check.
If possible, I ask you to do this.

**Comment by ordeh** [comment]
Fixed, the time of the event will be tied to the time zone in which the server is located.

@andrei9619 
Could you re-run test-case for this bug and provide results in the next comment?

**Comment by ordeh** [comment]
@AndreiByin 
Could you re-check event time tests and solve todo?
