### ISSUE TITLE
Reconnect system

### ISSUE THREAD

**Issue by ordeh** [tasks-delivery/MuOnline#141]
Reconnect time should have 30 sec

If the user has lost the connection with the game, then within 30 seconds the system will try to reconnect the user.

**Comment by ordeh** [comment]
@andrei9619
Test should be added to Character suite

**Comment by andrei9619** [comment]
Test located at:
https://app.qase.io/case/WOMU/edit/39

**Comment by ordeh** [comment]
@andrei9619 

Add that after lost connection we can see  loading bar or indicator 

![image](https://user-images.githubusercontent.com/25455982/135070865-2c0ce2b9-941e-41d6-b9ca-3cf531dce47d.png)

**Comment by andrei9619** [comment]
@ordeh 
Fixed
