### ISSUE TITLE
Vote in muonline.us

### ISSUE THREAD

**Issue by ordeh** [tasks-delivery/MuOnline#176]
As a user, I would like to receive WoCoins for voting. The voting system should be available in the right panel on the page after the user login.

At a minimum, there should be integration with the most popular USA rating platform MUONLINE.US

The user can vote only according to the rules of the rating platform, we are not responsible for the loss of votes due to the fault of the platform.

After the user has voted, the MUONLINE.US platform will check that the vote has been counted. If the rating platform confirms that the vote has been counted, we add 3 WoCoins to account of user.

According to the MUONLINE.US platform rules we can vote one time per 12 hours. There will be no warning or notification in case you try to re-vote earlier and the vote won't count.

**Comment by ordeh** [comment]
@andrei9619 
I think more test cases can be developed for this ticket.

**Comment by andrei9619** [comment]
@ordeh 
Done
Test located:
https://app.qase.io/case/WOMU/edit/73

**Comment by ordeh** [comment]
It is not login block

![image](https://user-images.githubusercontent.com/25455982/141086732-c15f4df7-3b3f-409e-85c0-0eb8b910e83b.png)
If the user is already logged in, he will see his personal account, please fix this in both test-cases.

Also, I miss understanding how you can leave vote in future ?? current date <date of vote

![image](https://user-images.githubusercontent.com/25455982/141086952-5bef28ae-5b2b-4caa-809f-ba139625acc5.png)

**Comment by andrei9619** [comment]
@ordeh 
Fixed

**Comment by ordeh** [comment]
@andrei9619 
I think that we need to change the WoCoins in preconditions is 3 and create a separate test-case where we will check that after voice we have +3 WoCoins
![image](https://user-images.githubusercontent.com/25455982/141672527-c422bc2b-e831-46bd-aa75-82d0eb51be79.png)

**Comment by andrei9619** [comment]
@ordeh 
Fixed.
Test cases:
Vote and receive 3 WOCOINs - https://app.qase.io/case/WOMU/edit/67
User can vote once per 12 hrs per voice - https://app.qase.io/case/WOMU/edit/94
User receives 3 WoCoins after voting - https://app.qase.io/case/WOMU/edit/73
