### ISSUE TITLE
System reconnects after 30sec being offline

### ISSUE THREAD

**Issue by andrei9619** [tasks-delivery/MuOnline#177]
**Precondition:**
1. at least one server exists in the system
2. user registered and signed in, at least one character exists

**Steps to reproduce:**
1. Chose server and character from precondition
2. Enter the game world 
3. Turn off Wi-Fi
4. Wait for 31 seconds
5. Turn on Wi-Fi

**Actual result:** System reconnects successfully
**Expected result:** Message about lost connection is shown

**Environment:**
Windows 10, Wi-Fi connection

**Comment by andrei9619** [comment]
Test located at:
https://app.qase.io/case/WOMU/edit/54

**Comment by ordeh** [comment]
@andrei9619 
Could you re-check this and update test-case
