### ISSUE TITLE
600 Stat points for dl after reset

### ISSUE THREAD

**Issue by ordeh** [tasks-delivery/MuOnline#178]
Heroes of this Dark Lord class should receive a reward for resetting 600 free stats points.

**Comment by ordeh** [comment]
The latest expected result should check 600 stat point according to description of test-case
![image](https://user-images.githubusercontent.com/25455982/139526402-dabd2b47-ca32-4a4b-832b-bedf28434fbc.png)

How you define necessary reset button?

![image](https://user-images.githubusercontent.com/25455982/139526460-ccf90e99-fb6f-4505-927d-bc1bfef9619d.png)

I think that you need to add in the first expected result, that 'character from preconditions is shown', and after that  you need to rework the second step, click 'reset' button near character from preconditions.
![image](https://user-images.githubusercontent.com/25455982/139526443-0af4a924-2b11-4e89-a606-d40bd6d943f9.png)

This step should be reworked, pless add that we fill login and password fields. This is not an bug report, everything should be as detailed as possible in the test-case

![image](https://user-images.githubusercontent.com/25455982/139526608-922f97ce-2854-4ec8-8c92-7a5f1587759e.png)

**Comment by andrei9619** [comment]
@ordeh 
Fixed
Test case located at:
https://app.qase.io/case/WOMU/edit/74
