### ISSUE TITLE
Wrong Raclion map name

### ISSUE THREAD

**Issue by andrei9619** [tasks-delivery/MuOnline#202]
**Precondition:**
Account exists in the system, chosen character has 280lvl or higher

**Steps to reproduce:**
1. Open WoMu game client
2. Enter credentials of account from precondition
3. Chose character from precondition
4. Click connect button
5. Press 'M' key
6. Scroll down and click on 'Raklion' map
 
**Actual result:** Map name shows 'La Cleon'
**Expected result:** Map name shows 'Raclion'

**Environment:** Windows 10, Wi-Fi connection

![Screen Shot 2021-10-05 at 8 21 47 PM](https://user-images.githubusercontent.com/61422820/136121430-3051510f-5345-43a0-a9a5-b9e2eaef0fc2.png)

**Comment by ordeh** [comment]
@andrei9619 
Now the map in the list for the teleport will have a name **LaCleon**

**Comment by andrei9619** [comment]
@ordeh
The bug has been fixed in release 1.2.1
