### ISSUE TITLE
It is possible to add negative stats

### ISSUE THREAD

**Issue by ordeh** [tasks-delivery/MuOnline#210]
**Preconditions**: The user has already entered his personal account on the site

**Steps**:
1. Click on Services link
2. Click stat setup link
3. Type -1 value in the Vitality field
4. Click Continue button

**Actual result**: Stats are saved
**Expected result**: Stats are not saved and error message with text 'You cannot set the value less than 0' is shown

**Comment by andrei9619** [comment]
Test located at 
https://app.qase.io/case/WOMU/create

**Comment by ordeh** [comment]
@andrei9619 
Why you describe stat reset link?

![image](https://user-images.githubusercontent.com/25455982/141867844-491a0ed3-d9cd-4c6b-9247-9cb8e68815ff.png)

I think that it can be removed, because in this case we should check behavior only for setup stat function.

**Comment by andrei9619** [comment]
@ordeh 
Fixed
