### ISSUE TITLE
We have an error with the text "VOTE AND RECEIVE VIP"

### ISSUE THREAD

**Issue by AndreiByin** [tasks-delivery/MuOnline#260]
We have an error with the text "VOTE AND RECEIVE VIP" due to a case mismatch in the application and the JSON file.
Precondition:

1. Account exists in the system
2. At least one server exists in the system

Steps to reproduce:

1. Open the web application
2. Type login of the account from precondition
3. Type password 
4. Select server from precondition
5. Click ‘login’
6. Click 'Vote'

**Actual result:** "VOTE AND RECEIVE VIP"
**Expected result:** JSON file should have key 'Vote and receive VIP' and value Vote and receive VIP in upper-case
**"VOTE AND RECEIVE VIP"**
Please change the case in the link name in value

Also please check the translator for the Russian 

![image](https://user-images.githubusercontent.com/56843265/140260507-e34611be-d57e-4d96-8adf-80c5a1b1951a.png)
![image](https://user-images.githubusercontent.com/56843265/140260558-107e448b-a84c-4728-8107-7effa45ee9d0.png)

**Comment by ordeh** [comment]
@AndreiByin 
Could you clarify expected result? without the expected result, I cannot figure out what is wrong

If you meant that the text should be in lower case, then this is not the case. This is a button component, in the layout it always composes buttons and has uppercase text, these are the features of the framework.

Regarding translation everything is okay

![image](https://user-images.githubusercontent.com/25455982/140617490-70239696-9493-4279-8b2c-dcae6bfd91eb.png)

**Comment by AndreiByin** [comment]
the fix was checked. Done
