### ISSUE TITLE
Sql exception after add stats by command 'addstr'

### ISSUE THREAD

**Issue by ordeh** [tasks-delivery/MuOnline#27]
**Preconditions**: Account with DL with 7 free stats exists in the system

**Steps**:
1. Login as account from preconditions and join under DL character
2. Press 'Enter' key on keyboard and type '/addstr 1' command
3. Press 'Enter' key on keyboard
4. 
**Actual result**: SQL exception is shown

![image](https://user-images.githubusercontent.com/25455982/120516255-d1ca1980-c3d7-11eb-9313-f896c9605f7d.png)

**Expected result**: 1 str stat was added to total str of character and SQL exception is not shown

**Comment by ordeh** [comment]
Add stat command was changed to /str, /vit and so on.

**Comment by ordeh** [comment]
@andrei9619 
Test should be added to Stat Point suite

**Comment by andrei9619** [comment]
Test located at:
https://app.qase.io/case/WOMU/edit/40

**Comment by ordeh** [comment]
@andrei9619 
Add that input line is shown for step 3 and value '/addstr1' is displayed  in input line  for step 4

![image](https://user-images.githubusercontent.com/25455982/134637332-251232c1-c53b-4a92-ad99-3b03ffc245dc.png)

**Comment by ordeh** [comment]
@andrei9619 
Why you check that SQL exception is shown?

![image](https://user-images.githubusercontent.com/25455982/134809095-828543ae-08f3-4d1e-bebd-ec0f1359caef.png)

We should check that SQL exception is not shown

**Comment by andrei9619** [comment]
@ordeh 
Fixed. Thank you
