### ISSUE TITLE
Bug in the JSON file

### ISSUE THREAD

**Issue by AndreiByin** [tasks-delivery/MuOnline#277]
We have a bug with a test that does not match each other in the application and the JSON file.

**Precondition:**
1. Account exists in the system
2. At least one server exists in the system

**Steps to reproduce:**
1. Open the web application
2. Type login of the account from precondition
3. Type password
4. Select server from precondition
5. Click ‘login’
6. Click 'Services'
7. Click 'Get VIP account'

**Actual result:** "Vip Buff:"
**Expected result:**  JSON file should have key 'Vip Buff' and value **"Vip Buff:"**

![image](https://user-images.githubusercontent.com/56843265/140639657-57ea520c-671a-43ed-9c16-2a0248bcd7d4.png)

![image](https://user-images.githubusercontent.com/56843265/140639594-ce679a9d-4db7-4029-b28a-7e2d9878ad30.png)

**Comment by ordeh** [comment]
Not a bug
