### ISSUE TITLE
Resolution improvement

### ISSUE THREAD

**Issue by andrei9619** [tasks-delivery/MuOnline#302]
Game client Resolution has to match all major screen resolutions full screen

![Screen Shot 2021-11-11 at 11 45 27 AM](https://user-images.githubusercontent.com/61422820/141336090-13daeb6d-cb9e-4dab-87ad-f110774b26e7.png)

**Comment by ordeh** [comment]
Duplicate https://github.com/tasks-delivery/MuOnline/issues/560
