### ISSUE TITLE
Logout doesn't work (Firefox browser)

### ISSUE THREAD

**Issue by andrei9619** [tasks-delivery/MuOnline#307]
**Precondition**
User signed up to the womu.by platform

**Steps to reproduce**
1. Login to the womu.by
2. Click 'Logout' button 

**Actual result:** user still logged in

**Expected result:** user signed out, login form is shown

**Environment** MacOS, Mazilla Firefox browser

**Comment by andrei9619** [comment]
@ordeh 
The bug has been fixed

**Comment by ordeh** [comment]
@andrei9619 

Unfortunately the bug is reproducible

**Comment by andrei9619** [comment]
@ordeh 
The bug has been fixed in release 1.2.1
