### ISSUE TITLE
vote with MMOTOP.RU 

### ISSUE THREAD

**Issue by andrei9619** [tasks-delivery/MuOnline#310]
**Precondition**
1. User signed up and logged in to the womu.by platform
2. User's womu account name is 'andre96'
3. Character with name 'Andre96' exists in the system
3. User registered on MMOTOP.RU 

**Steps to reproduce**
1. Click vote in the login block
2. Click vote and receive Vip
3. Follow instructions, enter Andre96 with capital 'A', and vote for the exline x1000 
4. Wait for an hour
5. Go to the womu.by/account/services/vip

**Actual result:** 'GET' button is disabled for bronze Vip

**Expected result:** 'GET' button is enabled for bronze Vip

**Comment by andrei9619** [comment]
@ordeh
The bug has been fixed in release 1.2.1

**Comment by ordeh** [comment]
@andrei9619 
Could you create test-case for this ticket?

**Comment by andrei9619** [comment]
@ordeh 
Done
Test Case located at:
https://app.qase.io/case/WOMU/edit/98

**Comment by ordeh** [comment]
@andrei9619 
We need to check that vote is accepted from our side. It is possible to check by wait 2-3 hours and check VIP button in vip services.

**Comment by andrei9619** [comment]
@ordeh 
Fixed
