### ISSUE TITLE
Specific description for Devil Square ranking

### ISSUE THREAD

**Issue by ordeh** [tasks-delivery/MuOnline#336]
Add 'Scores will only be added from Devil Square level 5 and above.' text in Devil Square ranking description

**Comment by ordeh** [comment]
@andrei9619 

Could you updated Devil Square ranking test?

**Comment by andrei9619** [comment]
@ordeh 
Test case located at:
https://app.qase.io/case/WOMU/edit/111

**Comment by andrei9619** [comment]
@ordeh 
Can you take a look at the test case please and I will also create  test case for negative scenario

**Comment by ordeh** [comment]
@andrei9619 

Everything is fine, I look forward to more test cases for this task from you.

**Comment by andrei9619** [comment]
@ordeh 
Test cases:
Positive - https://app.qase.io/case/WOMU/edit/111
Negative - https://app.qase.io/case/WOMU/edit/113

**Comment by andrei9619** [comment]
@ordeh 
Do we need a better coverage? or 2 test cases will be enough for this ticket?
We also have 3 more test cases covering Devil Square ranking

**Comment by ordeh** [comment]
@andrei9619 
I'm not sure that Blood castle word should be placed in there
![image](https://user-images.githubusercontent.com/25455982/145002527-1676cb66-3ba9-49a6-a1ed-5126ccaa8716.png)
Also, please re-check all test-cases
![image](https://user-images.githubusercontent.com/25455982/145002687-51a91194-edea-4dff-b83c-de8d3c2758c3.png)

I think that we should check text only in one test-case, for instance in there https://app.qase.io/case/WOMU/edit/79

Please remove duplicate checks from another test-cases
![image](https://user-images.githubusercontent.com/25455982/145002902-8207ab32-a29c-4c00-9820-ecadac2092c4.png)


Where we check text?
![image](https://user-images.githubusercontent.com/25455982/145003100-8efc3654-afc8-4504-8c2b-8a235fbf09fa.png)

**Comment by andrei9619** [comment]
@ordeh 
Fixed
