### ISSUE TITLE
Blood castle timer

### ISSUE THREAD

**Issue by ordeh** [tasks-delivery/MuOnline#357]
In the game client, the quest runs on schedule at 18.30, but this time is not on the site
![image](https://user-images.githubusercontent.com/25455982/143054127-dff0a00a-baf0-43ae-93c3-bde5656d6806.png)

**Preconditions**: Now time is 18.00

**Steps**:
1. Open web applicaton

**Actual result**: The Blood Castle event is displayed on the website at 20:30.
**Expected result**: The Blood Castle event is displayed on the website at 18:30.

**Comment by ordeh** [comment]
@andrei9619 
Just test this without test-case development after release 1.2.3

**Comment by andrei9619** [comment]
@ordeh 
The issue has been fixed and tested
