### ISSUE TITLE
Statistics page is crashing after delating a guild

### ISSUE THREAD

**Issue by andrei9619** [tasks-delivery/MuOnline#361]
**Precondition:**
1. User signed up and logged in to the web platform
2. At least one character exists in the system
3. At least one guild exists in the system 

**Steps to reproduce:**
1. Open the game client 
2. Choose the character from precondition and click connect button
3. Press 'G' key on the keyboard
4. Select the guild from precondition
5. Click 'Disband'
6. Close the game client 
7. Go to the womb.by
8. Click statistics link from the header
9. Hover mouse to the 'Move mouse' underlined link  

**Actual result:** Page opened with 500 error

![image](https://user-images.githubusercontent.com/25455982/142918291-81d0d163-f2ab-40b1-a22a-9ca207d33e74.png)

**Expected result:** Statistic page opened, guild no longer shown in the 'Registered guilds' list

**Comment by andrei9619** [comment]
Test case located at:
https://app.qase.io/case/WOMU/edit/102

**Comment by ordeh** [comment]
@andrei9619 
Guild should be registred in Castle siege event

![image](https://user-images.githubusercontent.com/25455982/143314384-677a07f3-c52b-421f-aa12-cfe52b7a6fd7.png)


Remove steps 1, 2 and 3, it is redundant.

![image](https://user-images.githubusercontent.com/25455982/143314459-cc139242-27f6-4969-a0d6-2ddf6a249fb6.png)

Character exists in the system, but he is participant of guild? I think that we need to add that character  participant of guild

![image](https://user-images.githubusercontent.com/25455982/143314575-ba92b166-44f7-4435-97d9-44fdbb4c9fe5.png)

Why you use hardcoded name of guild 'Abc123'? I think that we can use just guild from preconditions It doesn't matter what the name of this guild has

![image](https://user-images.githubusercontent.com/25455982/143314696-84efa51c-0558-420e-bde7-7f9d48b39fcd.png)

**Comment by andrei9619** [comment]
@ordeh 
Fixed

**Comment by ordeh** [comment]
Remove map from preconditions

![image](https://user-images.githubusercontent.com/25455982/143317333-8179edca-9d8d-447c-b45c-ad787c8c7fb0.png)


Add step. 
![image](https://user-images.githubusercontent.com/25455982/143317371-4f03310b-a661-49c7-83cc-38b92a495c22.png)

When user open guild popup by default we can see member tab, we need to switch to Guild tab and after that  we can use Disband button.

![image](https://user-images.githubusercontent.com/25455982/143317458-c18956ac-c412-4f47-96b7-592813efbd83.png)
