### ISSUE TITLE
Statistics classes block percentage accuracy 

### ISSUE THREAD

**Issue by andrei9619** [tasks-delivery/MuOnline#367]
**Precondition:** 
1. Server 'Exile 1000' exists in the system 

**Steps to reproduce:**
1. Go to womu.by
2. Click 'Statistics' tab located at the header
3. Click on server from precondition and scroll down to the 'Classes'
 
**Actual result:** Percentage is not accurate
**Expected result:** Percentage is not accurate

**Comments:** If we take the first character 'Magic Gladiator, they're 20 of them shown in the grid. Total amount of all characters are 392, so we can calculate percentage of the 'Magic Gladiators' (20*100) / 392 = 5,1%

![Screen Shot 2021-11-25 at 4 11 02 PM](https://user-images.githubusercontent.com/61422820/143500197-977e1f93-eece-4301-8bc0-8fe3efe3aefa.png)

**Comment by ordeh** [comment]
Please re-check this in production

**Comment by andrei9619** [comment]
@ordeh 
The issue has been fixed and tested
