### ISSUE TITLE
Download page, Full client and Cloud icon issue

### ISSUE THREAD

**Issue by andrei9619** [tasks-delivery/MuOnline#375]
**Steps to reproduce:**
1. Open womb.by
2. Click 'Download' link in the header
3. Click 'Full Client Exile x1000:Full client' link 

**Actual result:** Nothing happened

**Expected result:** Download go the full client started

**Comments:** Same for the cloud icon

**Comment by ordeh** [comment]
@andrei9619 
just test this in production

**Comment by andrei9619** [comment]
@ordeh 
Issue has been fixed and tested
