### ISSUE TITLE
Teleport duel

### ISSUE THREAD

**Issue by ordeh** [tasks-delivery/MuOnline#381]
![image](https://user-images.githubusercontent.com/25455982/144278676-3fc6bb1f-126f-4e42-aa3f-09b7e813547d.png)

![image](https://user-images.githubusercontent.com/25455982/149594865-0c6cd062-f0b2-4ee1-a0ee-56c3cd1e4ba2.png)

**Comment by YuryiDasevich** [comment]
**Description:**
1) regardless of SM stats (full or not) it is not possible to make more than 2 strikes of any skill from "Teleport"
2) seen in Duel and out of Duel zone. Confirmed by @xJust1ce
