### ISSUE TITLE
Item can be sold and bought for 0 WoCoins 

### ISSUE THREAD

**Issue by andrei9619** [tasks-delivery/MuOnline#388]
**Precondition:**
1. User registered and signed up to womu.by
1. At least one item exists in the Virtual Vault

**Steps to reproduce:**
1. Click 'Market' link
2.  Click 'Virtual Vault' drop down
3. Click 'SELL' button
4. Enter 0 to the price field
5. Click 'SELL' button 

**Expected result:** Item transferred to the market, price is 0 WoCoins
**Actual result:** Error window with price requirements popped up

**Comments:**
Item can also be bought for 0 WoCoins

![Screen Shot 2021-12-09 at 11 51 06 AM](https://user-images.githubusercontent.com/61422820/145440183-bf0ce604-fcb0-4312-9059-c32b8344c4cb.png)
![Screen Shot 2021-12-09 at 11 51 19 AM](https://user-images.githubusercontent.com/61422820/145440221-ca75b952-9eba-46b8-a528-7a8afb9a1ef6.png)

**Comment by ordeh** [comment]
Fixed.

In this case message with test 'You cannot sell item for 0 price.' should be visible.

**Comment by andrei9619** [comment]
@ordeh 
Tested 
Test case located at: https://app.qase.io/case/WOMU/edit/133?view=2

**Comment by ordeh** [comment]
@andrei9619 
Could you update test-case? validation message was changed to 'Item price must be greater than 0.'. This releated to issue #394

**Comment by veyron812** [comment]
@ordeh 
Test-case was updated, validation mesage was changed.
