### ISSUE TITLE
Error message overlapped and unreadable

### ISSUE THREAD

**Issue by veyron812** [tasks-delivery/MuOnline#389]
**Precondition:**

1. User registered and signed up to womu.by
2. At least one item exists in the Market
3. User has 0 coins

**Steps to reproduce:**

1. Click 'Market' link
2. Click on item in 'Found items' list
3. Click 'BUY' button
 
**Actual result**: Error window overlapped by confirmation window. Error window unreadable.

**Expected result**: Error window not overlapped

![Overlap jpeg](https://user-images.githubusercontent.com/95405000/145469997-4c18b72b-89af-4e37-8c3c-491fbdfe2a35.png)

**Comment by veyron812** [comment]
bug fixed

**Comment by ordeh** [comment]
@veyron812 

Could you update test-case? validation message was changed to 'Item price must be greater than 0.'. This releated to issue #394

**Comment by veyron812** [comment]
@ordeh 
changed validation message in test-case
