### ISSUE TITLE
Wrong language after purchase in shop

### ISSUE THREAD

**Issue by veyron812** [tasks-delivery/MuOnline#391]
**Precondition:**

User registered and signed up to womu.by
User changed language to Russian

**Steps to reproduce:**

1. Click 'Магазин' link
2. Buy 1 item in the shop

**Actual result:**
User has informational message in English

**Expected result:**
User has informational language in Russian

![WrongLanguage](https://user-images.githubusercontent.com/95405000/145474894-ef0b1a90-94cd-40c2-a228-6650e47e693e.jpg)

**Comment by veyron812** [comment]
Bug fixed

**Comment by ordeh** [comment]
@veyron812 
Remove this test-case. 

Test cases for localization other than English are redundant.

**Comment by veyron812** [comment]
@ordeh 
test-case was deleted
