### ISSUE TITLE
No confirmation before removing item from sale list

### ISSUE THREAD

**Issue by veyron812** [tasks-delivery/MuOnline#392]
**Precondition:**

1. User registered and signed up to womu.by
2. User has at least 1 item placed for sale

**Steps to reproduce:**

1. Click 'Market' link
2. Click 'Take back' in 'Found items'

**Actual result:**
Item removed from sale list without confirmation

**Expected result:**
System asks confirmation before removing

https://user-images.githubusercontent.com/95405000/145477937-46a5bfd1-011b-44dc-b85f-5eee2e6791c9.mp4

**Comment by ordeh** [comment]
All back actions was implemented without confirmation box. The same for return in game warehouse from the Virtual Vault.
