### ISSUE TITLE
Wrong count of free slots in Market

### ISSUE THREAD

**Issue by veyron812** [tasks-delivery/MuOnline#395]
**Precondition:**

User registered and signed up to womu.by
User has at least 1 item in Virtual bank
User has free slots for trading

**Steps to reproduce:**

1. Click 'Market' link
2. Open dropdown 'Virtual vault'
3. Click 'Sell' button
4. Input price
5. Click 'Sell'

**Actual result:**
Text 'You have 20 free trading slots for WoCoins'

**Expected result:**
Text 'You have 19 free trading slots for WoCoins'

![FreeSlots](https://user-images.githubusercontent.com/95405000/145626234-453c9839-21ab-47b7-9e71-e88ad911d040.jpg)

**Comment by ordeh** [comment]
This is not a bug, it displays the total number of slots that the user has.

I was changed text to 'You have 40 trading slots for WoCoins'

Please re-check this

**Comment by veyron812** [comment]
@ ordeh
yes, that's not a bug
yes, text was changed

**Comment by veyron812** [comment]
We can add this feature in future. System should count how many free trading slots does user have. 
Example;
1) User has 30 trading slots
2) User put 24 items for sale.
System still will show text 'You have 30 trading slots'? 
How user will know that he has 6 free slots? Does he need to count manually?

**Comment by ordeh** [comment]
@veyron812 
Great idea. Could you create separate ticket for this? with 'enhancement' label instead bug.

**Comment by veyron812** [comment]
@ordeh 
created enhauncment
https://github.com/tasks-delivery/MuOnline/issues/424
