### ISSUE TITLE
Item remove from sale list

### ISSUE THREAD

**Issue by veyron812** [tasks-delivery/MuOnline#396]
Precondition:

User registered and signed up to womu.by
User has at least 1 item for sale in Market

Steps to reproduce:

1. User does not make any steps.

Actual result:
Item placed for sale removed from sale list to Virtual vault

Expected result:
Item is on for sale list

![Dissapear](https://user-images.githubusercontent.com/95405000/145628230-dbb7e079-76c3-4bc7-af36-b0190efacdc9.jpg)

**Comment by veyron812** [comment]
I didn't do anything with item for sale. It removed to Virtual vault by itself

**Comment by ordeh** [comment]
@veyron812 
Most likely 15 minutes have passed. As we discussed on the skype call, if the item was not sold in a month, then it will return to the virtual vault. Now we have 15 minutes set for testing instead of one month. Please double check this.

**Comment by veyron812** [comment]
@ordeh 
According to Skype information return time now changed from 15 min to 1 day in testing purposes.
Need to wait till tomorrow to check this functionality.

**Comment by veyron812** [comment]
@ordeh 
tested
item remove in 1 day
