### ISSUE TITLE
Wrong Error message text

### ISSUE THREAD

**Issue by veyron812** [tasks-delivery/MuOnline#397]
Precondition:

User registered and signed up to womu.by
User has 0 coins

Steps to reproduce:

Click 'Shop' link
Click on item in Shop list
Click 'Purchase' 
Click Yes on confirmation page

Actual result: 
Error window with text 'Warehouse not activated. Visit your warehouse in the game'

Expected result:
Error window with text 'You need more WoCoins in server'

![4](https://user-images.githubusercontent.com/95405000/145690332-431b0888-88bc-4461-b0ef-b93312579de5.jpg)

**Comment by ordeh** [comment]
@veyron812 
I do not see that you have activated the warehouse in the preconditions.
This can only be considered a bug if your warehouse is activated. Double check this please.

**Comment by veyron812** [comment]
@ordeh 
this is not a bug.
