### ISSUE TITLE
Items not shown in Virtual Vault

### ISSUE THREAD

**Issue by veyron812** [tasks-delivery/MuOnline#400]
Precondition:

1. User signed up and signed in to womu.by
2. At least one server exists in the system
3. At least one character exists in that account
4. User has opened warehouse in the game client
5. User has at least 1 item in Virtual Vault
6. Game client is offline

Steps to reproduce:

Click 'Virtual vault'

Actual result:
Items not shown in Virtual Vault

Expected result:
Items are shown in Virtual Vault list

Comment; at the same time items are shown in Virtual Vault dropdown list on Market page

![7](https://user-images.githubusercontent.com/95405000/145692120-c294a362-105e-4e01-b815-2409fd7e187e.jpg)

![6](https://user-images.githubusercontent.com/95405000/145692114-a046e2ec-edc2-495a-bd34-9acfe8af17c0.jpg)

**Comment by ordeh** [comment]
@veyron812 

Why didn't you add that the warehouse is not activated? it's important

Reason:

![image](https://user-images.githubusercontent.com/25455982/145709277-520c41f2-4582-4bd5-a8dc-a63b3de5c084.png)

Fixed, validation message was added.

**Comment by veyron812** [comment]
@ordeh 
tested
changed preconditions
