### ISSUE TITLE
Help bonus component for new users

### ISSUE THREAD

**Issue by ordeh** [tasks-delivery/MuOnline#408]
New users should be able to get a starter help package.

The starter pack can be obtained on a separate page, which can be accessed through a link 'Starter pack' in the account panel.

If the user has already activated the starter pack, then upon going to the page for receiving the starter pack, the system will immediately generate an error with the text **You have already used the starter pack**

The Starter pack page should have hint for users in text 

`You can activate the newbie pack only 1 time for your account. The system will offer you to apply the starter pack to a character that does not have grand resets and below 30 resets.`

Also, part of text should have bold style
`After activating the starter pack, you need to make a reset, then you will receive free stats points for 31 resets.`

The page should contain a 'Activate' button to activate the starter pack and a drop-down list with available characters

If the user account is online in the game, then the system displays an error with the text **The account must not be online in the game**

After successful activation of the package, the user should see a message in a green box with text **Starter pack activated**

**Comment by andrei9619** [comment]
@ordeh 
1. https://app.qase.io/case/WOMU/edit/148
2. https://app.qase.io/case/WOMU/edit/149
3. https://app.qase.io/case/WOMU/edit/150
4. https://app.qase.io/case/WOMU/edit/151
5. https://app.qase.io/case/WOMU/edit/152

**Comment by ordeh** [comment]
@andrei9619 
**Test-case 148:**

Remove items 2, 3 and 4
![image](https://user-images.githubusercontent.com/25455982/146829150-f4ed4299-a14e-455e-8c65-b10e53b0f181.png)

Test-case 149:

The character does not get + 30 resets to the existing ones, he just gets 30 resets.
![image](https://user-images.githubusercontent.com/25455982/146829407-21815ae9-5df9-4f6f-944d-8463a063ecab.png)

**Comment by andrei9619** [comment]
@ordeh  
Fixed
