### ISSUE TITLE
There are no column names in latest item market block

### ISSUE THREAD

**Issue by veyron812** [tasks-delivery/MuOnline#412]
Precondition:
At least one server exists in the system

Steps to reproduce:

1. Open link
https://womu.by/
2. Scroll page down

Actual result:
 Latest item market block has 2 columns without names

Expected result:
 Latest item market block has 2  columns with names 'Item' and 'Price

![9](https://user-images.githubusercontent.com/95405000/146132582-88462aa4-0271-4914-9126-ac8f5ceb483f.jpg)
'

**Comment by ordeh** [comment]
It was bug in requirements. I updated ticket description https://github.com/tasks-delivery/MuOnline/issues/403

@veyron812 You can update test-cases

**Comment by veyron812** [comment]
@ordeh 
updated test-case
https://app.qase.io/project/WOMU?view=1&suite=31&case=141
