### ISSUE TITLE
Wrong sorting items placed for sale

### ISSUE THREAD

**Issue by veyron812** [tasks-delivery/MuOnline#413]
Precondition:

User signed up and signed in to womu.by
At least one server exists in the system
At least one character exists in that account
User has opened warehouse in the game client
User has 10 items in the 'Vitrual Vault'
No item was placed on sale

Steps to reproduce:

1. Click 'Market' link
2. Click on 'Virtual Vault' dropdown list
3. Click 'Sell' button on item from precondition
4. Enter number in price field
5. Click SELL button
6. Repeat 1-5 steps 9 times

Actual result:
10 items from preconditions are shown in Found Items grid and have no sorting. They placed in grid randomly.

Expected result:
10 items from preconditions placed for sale. Items are shown in Found Items grid and sorted accordingly they were placed for sale.
Lastest item placed for sale - on the top of the list and so on

Comment. 1)Items has correct sorting in the Latest market item block
                  2) I placed first item for sale with price 1, second item with price 2 and so on.
3) the same bug is on 'Your Items on market' grid

![10](https://user-images.githubusercontent.com/95405000/146135311-88da4cbb-9403-401f-acc0-d5a3043efbf4.jpg)
![11](https://user-images.githubusercontent.com/95405000/146135324-7a65e55b-0e30-4b66-a4bb-f3a0e2b83efa.jpg)
![13](https://user-images.githubusercontent.com/95405000/146136927-7121d9d3-7075-4da6-a900-75b3046a919e.jpg)

**Comment by ordeh** [comment]
@veyron812 
Could you re-check preconditions?

![image](https://user-images.githubusercontent.com/25455982/146267868-9321498b-346c-4fd8-b62d-58ea2548a0e6.png)

**Comment by andrei9619** [comment]
@ordeh 
Issue is still there
![Screen Shot 2021-12-15 at 5 01 11 PM](https://user-images.githubusercontent.com/61422820/146271870-8a8f3f44-9714-4bc7-af5f-3a08b631dc67.png)

**Comment by andrei9619** [comment]
@ordeh 
The issue has been fixed and tested
