### ISSUE TITLE
Items go to the end of the Find items list 

### ISSUE THREAD

**Issue by andrei9619** [tasks-delivery/MuOnline#417]
**Precondition:**
User has item in the Virtual Vault

**Steps to reproduce:**
1. Go to womu.by
2. Click 'Market' link
3. Click 'Virtual Vault' dropdown
4. Click 'Sell' button for the Item from precondition
5. Enter 1 to the 'Price' field
6. Click 'SELL' button

**Actual result:** Item moved to the end of the Found items list
**Expected result:** Item moved to the top of the Found items list

**Comment:** Same information parsing to the 'Item Market. Last items added on players market Exile'

**Comment by ordeh** [comment]
@andrei9619 
I think that we already have similar issue #413 Could you re-check this?

**Comment by andrei9619** [comment]
@ordeh
The issue has been fixed and tested
