### ISSUE TITLE
System adds extra option when user buy helm with option: HP+MANA+REF

### ISSUE THREAD

**Issue by andrei9619** [tasks-delivery/MuOnline#425]
**Precondition:**
* User has 1000 wocoins on the account
* User has previously opened the warehouse in the game client

**Steps to reproduce:**
1. Click 'Shop' link
2. Click 'Fairy Elf' drop down
3. Click 'Helm' dropdown
4. Click 'Seraphim Helm'
5. Check 'Reflect Damage', 'Increase Max Mana', 'Increase Max HP' boxes
6. Click 'Purchase' button 
7. Click 'Virtual Vault link
8. Hover mouse to the 'seraphim Helm' icon

**Actual result:** Seraphim helm shows options: **Increase acquisition rate of Zen after hunting monsters +40%**, Defense success rate +10%, Increase Max Mana +4%, Increase Max HP +4% 
**Expected result:** Seraphim helm shows options: Defense success rate +10%, Increase Max Mana +4%, Increase Max HP +4% 
![Screen Shot 2021-12-16 at 1 23 30 PM](https://user-images.githubusercontent.com/61422820/146427495-1341e66d-5299-421d-8347-c44c34973ac5.png)
![Screen Shot 2021-12-16 at 1 23 40 PM](https://user-images.githubusercontent.com/61422820/146427516-805aa9a7-223f-4a7e-a01a-a6e16bb9b480.png)

**Comment by veyron812** [comment]
@ordeh 
tested
tested on Fairy Elf - helms - Seraphime Helm with 4 options:
HP + MANA + ZEN
HP + MANA + DSR
HP + MP + REF
HP + MP + DSR + ZEN
