### ISSUE TITLE
Price limit error 

### ISSUE THREAD

**Issue by andrei9619** [tasks-delivery/MuOnline#427]
**Precondition:**
User has Great Reign Crossbow in the Virtual Vault

**Steps to reproduce:**
1. Go to womu.by
2. Click 'Market'
3. Click 'Virtual Vault' dropdown
4. Click on Great Reign Crossbow
5. Enter 10000000000 to the 'price field
6. Click 'Sell' button

**Actual Result:** Error '[object Object]' popped up

**Expected Result:** Error 'Max limit can be 100000'

![Screen Shot 2021-12-17 at 9 35 13 AM](https://user-images.githubusercontent.com/61422820/146560288-b9441a38-b0ba-451d-a054-05d24369b225.png)

**Comment by veyron812** [comment]
@ordeh 
tested
