### ISSUE TITLE
Trading slots error when Taking back item from the market

### ISSUE THREAD

**Issue by andrei9619** [tasks-delivery/MuOnline#428]
**Precondition:**
User has 7 items in the Virtual Vault 
User has 3 items on the market
User has limit of 10 trading slots

**Steps to reproduce:**
1. Open womu.by
2. Click 'Market' link
3. Scroll down to the 'Found items' and click 'Take back' (item that user previously moved to the market)

**Actual result:** Error 'You cannot move to virtual vault more than 10 items. Buy more trading slots in the market section.' popped up
**Expected result:** Item moved back to the Virtual Vault

**Comment by veyron812** [comment]
@ordeh 
tested
