### ISSUE TITLE
No translation for Latest item market block

### ISSUE THREAD

**Issue by veyron812** [tasks-delivery/MuOnline#429]
Precondition:
At least 1 server exists in system

Steps to reproduce:
Open womu.by
Change language to Russia
Scroll down main page

Actual result: Latest item market block has header in English

Expected result: Latest item market block has header in English
![22](https://user-images.githubusercontent.com/95405000/146597758-4946bb4a-9bcb-4acb-9dcd-edfe7c82cb82.jpg)

**Comment by YuryiDasevich** [comment]
FYI @ordeh 
Expected result: Latest item market block has header in **Russian**
