### ISSUE TITLE
Wrong pagination count on 'Found Items' grid

### ISSUE THREAD

**Issue by veyron812** [tasks-delivery/MuOnline#433]
Precondition:
User signed un and signed in to womu.by
At least one server exists in the system

Steps to reproduce:

Click 'Market' link
Scroll down page to the end
Click 4 page link 

Actual result: 4 page has 27 rows in grid. 5 page exist. 5 page is empty
Expected result: 4 page has 27 rows in grid. 5 page DOES NOT exist.

![29](https://user-images.githubusercontent.com/95405000/147147582-950c77cf-c27c-41b5-bb0a-ba631b5afd4b.jpg)
![30](https://user-images.githubusercontent.com/95405000/147147603-12c31edb-5fa1-4743-8dd8-4e03908b23d3.jpg)

**Comment by ordeh** [comment]
@veyron812 
Could you  re-check? I updated develop environment

**Comment by veyron812** [comment]
@ordeh 
tested
