### ISSUE TITLE
Item page in shop does not scroll

### ISSUE THREAD

**Issue by veyron812** [tasks-delivery/MuOnline#435]
Precondition:
User signed un and signed in to womu.by
At least one server exists in the system

Steps to reproduce:

Click 'Shop' link
Click 'Fairy Elf' dropdown
Click 'Bows and crossbows' dropdown
Click 'Arrow viper bow'
Zoom screen 

Actual result: Item page does not scroll. User can not see 'Purchase' button
Expected result:  Item page has scroll. User can scroll down to 'Purchase' button

![34](https://user-images.githubusercontent.com/95405000/147149902-9e7f2b12-b33c-471a-a4d6-7b82675590a4.jpg)
![35](https://user-images.githubusercontent.com/95405000/147149913-bf50f051-212a-4019-8d14-dad14442ddc2.jpg)
![image](https://user-images.githubusercontent.com/25455982/142732691-42eeb95f-b719-43f8-adf4-463f7644c4a8.png)

**Comment by ordeh** [comment]
Duplicated

https://github.com/tasks-delivery/MuOnline/issues/337

Let's leave this task and I'll delete the other one because there is a better description

**Comment by ordeh** [comment]
Fixed by padding
