### ISSUE TITLE
It is not possible to get noob buff from elf

### ISSUE THREAD

**Issue by ordeh** [tasks-delivery/MuOnline#44]
**Preconditions**: Account with character 1 level exists in the system

**Steps**: 
1. Login as account from preconditions and join to game as character from preconditions
2. Go to elf 
3. Click to elf
**Actual result**: Elf is provide buff for hero but without visual effects

![image](https://user-images.githubusercontent.com/25455982/120554869-f5ef2000-c402-11eb-9cd5-820bdaef1598.png)

**Expected result**: Elf provide buff for hero with visual effects

**Comment by ordeh** [comment]
@andrei9619 
Tests should be added in Character suite.

**Comment by andrei9619** [comment]
Test located at:
https://app.qase.io/case/WOMU/edit/41
