### ISSUE TITLE
Items in the market register sensitive

### ISSUE THREAD

**Issue by andrei9619** [tasks-delivery/MuOnline#443]
**Precondition**:
1. User has an account with username: andrei9619
2. User has an item in the market

**Steps to Reproduce**:
1. Login to womu.by with user name Andrei9619
2. Click 'market' link

**Actual Result** Item from precondition has button 'BUY'
**Expected Result** Item from precondition has button 'Take Back'
![Screen Shot 2022-01-04 at 12 23 47 PM](https://user-images.githubusercontent.com/61422820/148099736-ecd2400f-9b5f-4a68-b886-2358c7df8f19.png)
![Screen Shot 2022-01-04 at 12 22 15 PM](https://user-images.githubusercontent.com/61422820/148099746-374f8264-7481-4ea0-b423-c5f8546ff187.png)

**Comment by andrei9619** [comment]
@ordeh 
The bug is still there
![Screen Shot 2022-01-08 at 10 02 34 PM](https://user-images.githubusercontent.com/61422820/148667563-ddb03c28-9dcd-426c-8eb8-f2b7777591ff.png)

**Comment by ordeh** [comment]
@xJust1ce 
Could you re-check this please?

**Comment by xJust1ce** [comment]
![баг магазин 1](https://user-images.githubusercontent.com/98263562/152653272-39bb199f-ea4a-4cb7-be45-a67a63a9c0b3.png)
![баг магазин 2](https://user-images.githubusercontent.com/98263562/152653278-212732dd-5ff4-457c-946a-3a1928682d80.png)
![баг магазин 3](https://user-images.githubusercontent.com/98263562/152653280-aaef84bd-d603-4ba6-859c-08d58d1745fc.png)
Everything is working correctly.

**Comment by xJust1ce** [comment]
![bk](https://user-images.githubusercontent.com/98263562/152989108-abc67861-05a1-4b32-bc71-4e019df7f2b0.png)
![bkbk](https://user-images.githubusercontent.com/98263562/152989112-364cbe88-cbc2-41d2-b853-43bbd77fe342.jpg)
![elf](https://user-images.githubusercontent.com/98263562/152989116-c354a34c-782c-4fa9-a67a-31bf0f4dccec.png)
![Elf2](https://user-images.githubusercontent.com/98263562/152989117-6e90a366-246d-4031-bae2-94cab9839846.png)

**Comment by xJust1ce** [comment]
Everything is working correctly now
