### ISSUE TITLE
Wrong level of move map

### ISSUE THREAD

**Issue by ordeh** [tasks-delivery/MuOnline#45]
**Preconditions**: Account with character 10 level exists in the system

**Steps**:
1. Login as account from preconditions and join to game as character from preconditions
2. Click 'M' key on keyboard and select Devias 3 map

**Actual result**: Message about level requirement is shown

![image](https://user-images.githubusercontent.com/25455982/120556431-2c2d9f00-c405-11eb-9548-2e6993c843a2.png)

![image](https://user-images.githubusercontent.com/25455982/120556414-25069100-c405-11eb-9bc5-70811e9275cc.png)

**Expected result**: Requirement level should the same as level in map list

**Comment by ordeh** [comment]
Fixed

**Comment by ordeh** [comment]
@andrei9619 
Test should be added to Teleport suite

**Comment by andrei9619** [comment]
@ordeh 
Should I create test case for the positive scenario, negative scenario or boundary condition ( 19 level -cannot teleport to the Devias 3, 20 level - is able to teleport to the Devias 3 ) ?

**Comment by ordeh** [comment]
Hi @andrei9619 
Yes, sure.

**Comment by andrei9619** [comment]
Test case located at:
https://app.qase.io/case/WOMU/edit/28

**Comment by ordeh** [comment]
@andrei9619 

Please update preconditions in all teleport tests, we need to add that character have not DL or MG classes, because DL and MG can be moved in devias 3 from 13 lvl

![image](https://user-images.githubusercontent.com/25455982/133170506-b4c3a6ea-d487-425b-822f-8ee449174714.png)

![image](https://user-images.githubusercontent.com/25455982/133170569-7da86c4b-a0aa-4d16-bd23-81b33db2beac.png)
