### ISSUE TITLE
Zen bug after death

### ISSUE THREAD

**Issue by ordeh** [tasks-delivery/MuOnline#46]
**Preconditions**: Account with character 20 level and 10.000 zen exists in the system

**Steps**:

1. Login as account from preconditions and join to game as character from preconditions
2. Press 'M' key on keyboard and select Devias 3 map
3. Find Elite Yeti and wait for Yeti kill hero.
4. Press 'V' key on keyboard

**Actual result**: Zen value is updated to 1.500.000.000
**Expected result**: Zen value cannot  more than zen value before death

**Comment by ordeh** [comment]
@andrei9619 
Test should be added to Character suite

**Comment by andrei9619** [comment]
Test located at:
https://app.qase.io/case/WOMU/edit/31
