### ISSUE TITLE
Update support block

### ISSUE THREAD

**Issue by ordeh** [tasks-delivery/MuOnline#484]

**Comment by xJust1ce** [comment]
live:.cid.10288bd39b9968a7
WoMu Support-Just1ce

**Comment by ordeh** [comment]
@xJust1ce 
Could you provide join link?  for instance, '**https://join.skype.com/invite/BI358PEwqh3s**'

**Comment by xJust1ce** [comment]
https://join.skype.com/invite/NXLQbMeZjJbk
