### ISSUE TITLE
It is not possible to create Guild

### ISSUE THREAD

**Issue by ordeh** [tasks-delivery/MuOnline#55]
**Preconditions**: Account with character 400 lvl and 1500.000.000 zen exists in the system

**Steps**: 
1. Login as user from preocnditions and join in game as character from preconditions.
2. Go to devias and find guild master npc
3. Click to guild master npc and click Create guild button
4. Type guild name and write guild icon
5. Click Next button

**Actual result**: Guild is not created
**Expected result**: Guild is created

**Comment by ordeh** [comment]
@andrei9619 
Tests should be added in the 'Guild' suite, please create this suite.

**Comment by andrei9619** [comment]
Test located at
https://app.qase.io/case/WOMU/edit/43

**Comment by ordeh** [comment]
@andrei9619 

Wrong suite

![image](https://user-images.githubusercontent.com/25455982/134635372-d1930af3-aefb-4d2a-a42e-a9c853e6c4bd.png)

![image](https://user-images.githubusercontent.com/25455982/134635398-67359fb1-2b2a-411b-87bc-a7c6ad7e87fc.png)

**Comment by ordeh** [comment]
@andrei9619 

We can see the 'Next' button after click on NPC, please move this.

![image](https://user-images.githubusercontent.com/25455982/134910726-e5ea0a6e-8eec-4faf-a1e4-c085103cb9c5.png)

**Comment by ordeh** [comment]
@andrei9619 
How you  check that guild is created?

![image](https://user-images.githubusercontent.com/25455982/135480498-7f9d12d7-a69b-466d-a2b9-7494f67480b0.png)

**Comment by ordeh** [comment]
We do not yet know whether the guild was created or not, we saw just the guild creation pup up was closed

![image](https://user-images.githubusercontent.com/25455982/135747916-7911a14e-d6fb-489b-9701-235a26b9db21.png)
