### ISSUE TITLE
Vote system

### ISSUE THREAD

**Issue by ordeh** [tasks-delivery/MuOnline#79]
As a user, I would like to receive bonuses in the game for voting. The voting system should be available in the right panel on the page after the user login.

At a minimum, there should be integration with the most popular rating platform MMOTOP.ru

The user can vote only according to the rules of the rating platform, we are not responsible for the loss of votes due to the fault of the platform.

After the user has voted, our system will check every minute that the vote has been counted. If the rating platform confirms that the vote has been counted, we provide the user with the opportunity to receive an award in the form of a VIP account.

VIP services are located in the section the **Services** section and find a block with **VIP services** there.
The user has the opportunity to receive 3 different levels of VIP services

The list of available VIP types with their parameters is shown below:
```
• Bronze Vip + 10% exp + 10% drop + 10% zen
• Silver Vip + 20% exp + 20% drop + 20% zen
• Gold Vip + 30% exp + 30% drop + 30% zen
```

Each type of VIP has its own requirements. Requirements matrix is shown below:
```
Voices	       Vip type
50 sms voices	Gold	
10 sms voices	Silver	
1 voice	       Bronze	
```

Each VIP is valid only 24 hours

**Comment by ordeh** [comment]
@andrei9619 
Could you provide links to the test-cases?

**Comment by andrei9619** [comment]
Tests located at:
https://app.qase.io/case/WOMU/edit/53
https://app.qase.io/case/WOMU/edit/52
https://app.qase.io/case/WOMU/edit/46
https://app.qase.io/case/WOMU/edit/61
https://app.qase.io/case/WOMU/edit/62
https://app.qase.io/case/WOMU/edit/63

**Comment by ordeh** [comment]
@andrei9619 
Please add texts of Timeline instruction and Vip Buff matrix in https://app.qase.io/case/WOMU/edit/53
![image](https://user-images.githubusercontent.com/25455982/136708528-4be2e665-c40d-40a2-87ce-4d251cd45d15.png)

Add in https://app.qase.io/case/WOMU/edit/52 that VOTE AND RECEIVE VIP is button
![image](https://user-images.githubusercontent.com/25455982/136708601-cefd9ae1-49f0-4299-b977-ea031b803a2a.png)

Rework text of message box in test-case https://app.qase.io/case/WOMU/edit/46
![image](https://user-images.githubusercontent.com/25455982/136708674-f89dda25-f68c-4106-af1d-3e0c6d0c8a72.png)
![image](https://user-images.githubusercontent.com/25455982/136708687-3a19942c-7bc5-4886-8a68-f83b8adb371a.png)
We also did not say that the hero from the preconditions is in the list, then we cannot use it.
![image](https://user-images.githubusercontent.com/25455982/136708746-4a0beda5-d3cc-45fd-b39b-3b0f260b5cb8.png)
Where should it appear?
![image](https://user-images.githubusercontent.com/25455982/136708799-a8b14c14-b061-4601-96c8-2c2bf8f5ad82.png)
Where map in preconditions?
![image](https://user-images.githubusercontent.com/25455982/136708858-89e2a867-90df-4ea4-bbb9-e5c1b4bbb1f5.png)
The same for https://app.qase.io/case/WOMU/edit/61 and https://app.qase.io/case/WOMU/edit/62

Rework text of message box in test-case https://app.qase.io/case/WOMU/edit/63
![image](https://user-images.githubusercontent.com/25455982/136708674-f89dda25-f68c-4106-af1d-3e0c6d0c8a72.png)
![image](https://user-images.githubusercontent.com/25455982/136708687-3a19942c-7bc5-4886-8a68-f83b8adb371a.png)

**Comment by andrei9619** [comment]
@ordeh 
Fixed

**Comment by AndreiByin** [comment]
@andrei9619 
Please correct the syntax error or it will fly into a bug report 
https://app.qase.io/case/WOMU/edit/52
![image](https://user-images.githubusercontent.com/56843265/140258387-1747a45a-aeec-4721-ab40-4db9ba12cd69.png)
