### ISSUE TITLE
Turn off reset command

### ISSUE THREAD

**Issue by ordeh** [tasks-delivery/MuOnline#8]
'**/reset**' command should be worked.

It is possible to make a reset only via web application

**Comment by ordeh** [comment]
@andrei9619 
Test should be added to Reset system suite

**Comment by ordeh** [comment]
@andrei9619 
Please provide link to test-case if this ready for review

**Comment by andrei9619** [comment]
Test located at 
https://app.qase.io/case/WOMU/edit/51
