### ISSUE TITLE
Hero level requirements for DL and MG

### ISSUE THREAD

**Issue by ordeh** [tasks-delivery/MuOnline#9]
Add requirement level for Dark lord 250 and  for Magic Gladiator 220

Link to wiki:

https://muonline.fandom.com/wiki/Characters

**Comment by ordeh** [comment]
@andrei9619 
Test should be added to Character suite

**Comment by ordeh** [comment]
@andrei9619 
Please provide link to test-case if this ready for review

**Comment by andrei9619** [comment]
Tests located at:
https://app.qase.io/case/WOMU/edit/49
https://app.qase.io/case/WOMU/edit/50

**Comment by ordeh** [comment]
@andrei9619 
User already logged, what he should not open
![image](https://user-images.githubusercontent.com/25455982/135295332-faa35b98-3fbe-419e-ae81-6a46ee1f5111.png)

I think that the first step can be removed

**Comment by andrei9619** [comment]
@ordeh 
Fixed

**Comment by ordeh** [comment]
@andrei9619 

Add test-cases that it is not possible to create mg with 219 level and dl with 249 level

**Comment by andrei9619** [comment]
@ordeh 
I added 2 negative Test Cases.
Location:
https://app.qase.io/case/WOMU/edit/58
https://app.qase.io/case/WOMU/edit/59

**Comment by ordeh** [comment]
@andrei9619 

Better to say that the hero should have level 219 for MG and the same for DL, but with level 249.

At this moment we can mis bug for instance, if run this test for hero  with 1 level.

![image](https://user-images.githubusercontent.com/25455982/135747717-1f8d71c9-1faa-4c77-98e8-b453b5191d3c.png)
