### ISSUE TITLE
Language is changed to EN after logout

### ISSUE THREAD

**Issue by ordeh** [tasks-delivery/MuOnline#90]
Cms should have EN and RU locale

**Preconditions**: Account exists in the system and RU language is selected in web application

**Steps**:
1. Open web application
2. Type name of account from preconditions into the login field on the login form
3. Type password of account from preconditions into the password field on the login form
4. Click 'Login' button
5. Click 'Logout' button

**Actual result**: Language is changed to EN
**Expected result**: Language is not changed

**Comment by ordeh** [comment]
Also, in this ticket we need to add multi-language support in our test system.

**Comment by andrei9619** [comment]
Test located at:
https://app.qase.io/case/WOMU/edit/34

**Comment by ordeh** [comment]
@andrei9619 

please add login and password fields in expected rseult for the first step

![image](https://user-images.githubusercontent.com/25455982/134637085-7f69dd93-4560-4808-bdab-a1369c0e4b86.png)

**Comment by ordeh** [comment]
@andrei9619 
We can see the Login button on the first expected result, please move this

![image](https://user-images.githubusercontent.com/25455982/134910965-7386e50a-c23b-4a69-a17d-3b4a13251b93.png)

**Comment by andrei9619** [comment]
@ordeh 
Fixed

**Comment by ordeh** [comment]
We cannot use Logout button, this element was not shown in the prevous expected result
![image](https://user-images.githubusercontent.com/25455982/135480217-7a13a0cd-cb19-4732-9add-5659ba3b69f8.png)
