### ISSUE TITLE
Login into game client with case sensitive

### ISSUE THREAD

**Issue by ordeh** [tasks-delivery/MuOnline#91]
**Preconditions**: Account  with login in upper case exists in the system, this account have one character

**Steps**:
1. Open game client mu online and select server Exile x1000
2. Type login in lower case of account from preconditions
3. Type password of account from preconditions and press Enter key on keyboard

**Actual result**: It is possible to join into account and character from preconditions is not shown
**Expected result**: It is possible to join into account and character from preconditions is shown

**Comment by ordeh** [comment]
Fixed by changing collation options in database

![image](https://user-images.githubusercontent.com/25455982/127030837-7c4607cd-e29c-4563-9f37-07d13718bb0d.png)

**Comment by ordeh** [comment]
@andrei9619
Test should be added to Character suite

**Comment by andrei9619** [comment]
Test located at:
https://app.qase.io/case/WOMU/edit/38
