### ISSUE TITLE
Wrong bless price

### ISSUE THREAD

**Issue by ordeh** [tasks-delivery/MuOnline#99]
**Preconditions**: Account with charcter with bless in inventory exists in the system

**Steps**:
1. Join into game as user from preconditions
2. Go to Lorencia map
3. Go to 'Lumen the Barmaid' shop
4. Click to 'Lumen the Barmaid' NPC
5. Hover mouse to bless from preconditions

**Actual result**: Bless price is not 3.000.000 zen

![image](https://user-images.githubusercontent.com/25455982/126055999-a84eec02-10be-4a8c-b60a-f4be3a2b9ce9.png)

**Expected result**: Bless price should be 3.000.000 zen

**Comment by ordeh** [comment]
@andrei9619
Test should be added to Character suite

**Comment by andrei9619** [comment]
Test located at:
https://app.qase.io/case/WOMU/edit/36

**Comment by ordeh** [comment]
Hi @andrei9619   could you rework expected result for step 4?

![image](https://user-images.githubusercontent.com/25455982/133170644-42b6e7c7-22ef-46f1-992d-fb5c901411ea.png)

Think about how to rephrase it
